### ISSUE TITLE
你快回来

### ISSUE THREAD

**Issue by 12345566-winky** [atcmorg/anticorgimurder#1]
is:issue is:open 你好啊 群里群主不小心失误给你踢出去了 我们都在找你 你有办法回来吗 赶紧回群里 谢谢你为小柯基们做出的努力啊 就是加不上你 看到了的话重新进群 可以先加我wx:winkyyunjing 我拉你进去

**Comment by anti-corgi-murder** [comment]
@12345566-winky thanks ~

**Comment by 12345566-winky** [comment]
you’re welcome :)


在 2021年4月25日 ***@***.***> 写道：


@12345566-winky thanks ~
